// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iter"
	"time"

	"github.com/davidteather/property-radar/internal/domain"
	"github.com/davidteather/property-radar/internal/ingest"
	"github.com/davidteather/property-radar/internal/photostore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPhotoCacher creates a new instance of MockPhotoCacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPhotoCacher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPhotoCacher {
	mock := &MockPhotoCacher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPhotoCacher is an autogenerated mock type for the PhotoCacher type
type MockPhotoCacher struct {
	mock.Mock
}

type MockPhotoCacher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPhotoCacher) EXPECT() *MockPhotoCacher_Expecter {
	return &MockPhotoCacher_Expecter{mock: &_m.Mock}
}

// Cache provides a mock function for the type MockPhotoCacher
func (_mock *MockPhotoCacher) Cache(ctx context.Context, provider string, sourceURL string) (ingest.CachedPhoto, error) {
	ret := _mock.Called(ctx, provider, sourceURL)

	if len(ret) == 0 {
		panic("no return value specified for Cache")
	}

	var r0 ingest.CachedPhoto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (ingest.CachedPhoto, error)); ok {
		return returnFunc(ctx, provider, sourceURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ingest.CachedPhoto); ok {
		r0 = returnFunc(ctx, provider, sourceURL)
	} else {
		r0 = ret.Get(0).(ingest.CachedPhoto)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, sourceURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPhotoCacher_Cache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cache'
type MockPhotoCacher_Cache_Call struct {
	*mock.Call
}

// Cache is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - sourceURL string
func (_e *MockPhotoCacher_Expecter) Cache(ctx any, provider any, sourceURL any) *MockPhotoCacher_Cache_Call {
	return &MockPhotoCacher_Cache_Call{Call: _e.mock.On("Cache", ctx, provider, sourceURL)}
}

func (_c *MockPhotoCacher_Cache_Call) Run(run func(ctx context.Context, provider string, sourceURL string)) *MockPhotoCacher_Cache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPhotoCacher_Cache_Call) Return(cachedPhoto ingest.CachedPhoto, err error) *MockPhotoCacher_Cache_Call {
	_c.Call.Return(cachedPhoto, err)
	return _c
}

func (_c *MockPhotoCacher_Cache_Call) RunAndReturn(run func(ctx context.Context, provider string, sourceURL string) (ingest.CachedPhoto, error)) *MockPhotoCacher_Cache_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockPhotoCacher
func (_mock *MockPhotoCacher) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPhotoCacher_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPhotoCacher_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockPhotoCacher_Expecter) Delete(ctx any, key any) *MockPhotoCacher_Delete_Call {
	return &MockPhotoCacher_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockPhotoCacher_Delete_Call) Run(run func(ctx context.Context, key string)) *MockPhotoCacher_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPhotoCacher_Delete_Call) Return(err error) *MockPhotoCacher_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPhotoCacher_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockPhotoCacher_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockPhotoCacher
func (_mock *MockPhotoCacher) Exists(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPhotoCacher_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockPhotoCacher_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockPhotoCacher_Expecter) Exists(ctx any, key any) *MockPhotoCacher_Exists_Call {
	return &MockPhotoCacher_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockPhotoCacher_Exists_Call) Run(run func(ctx context.Context, key string)) *MockPhotoCacher_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPhotoCacher_Exists_Call) Return(b bool, err error) *MockPhotoCacher_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPhotoCacher_Exists_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockPhotoCacher_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// EnrichDetail provides a mock function for the type MockSource
func (_mock *MockSource) EnrichDetail(ctx context.Context, sp ingest.SourceProperty) (ingest.SourceProperty, error) {
	ret := _mock.Called(ctx, sp)

	if len(ret) == 0 {
		panic("no return value specified for EnrichDetail")
	}

	var r0 ingest.SourceProperty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.SourceProperty) (ingest.SourceProperty, error)); ok {
		return returnFunc(ctx, sp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.SourceProperty) ingest.SourceProperty); ok {
		r0 = returnFunc(ctx, sp)
	} else {
		r0 = ret.Get(0).(ingest.SourceProperty)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ingest.SourceProperty) error); ok {
		r1 = returnFunc(ctx, sp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_EnrichDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrichDetail'
type MockSource_EnrichDetail_Call struct {
	*mock.Call
}

// EnrichDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - sp ingest.SourceProperty
func (_e *MockSource_Expecter) EnrichDetail(ctx any, sp any) *MockSource_EnrichDetail_Call {
	return &MockSource_EnrichDetail_Call{Call: _e.mock.On("EnrichDetail", ctx, sp)}
}

func (_c *MockSource_EnrichDetail_Call) Run(run func(ctx context.Context, sp ingest.SourceProperty)) *MockSource_EnrichDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ingest.SourceProperty
		if args[1] != nil {
			arg1 = args[1].(ingest.SourceProperty)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_EnrichDetail_Call) Return(sourceProperty ingest.SourceProperty, err error) *MockSource_EnrichDetail_Call {
	_c.Call.Return(sourceProperty, err)
	return _c
}

func (_c *MockSource_EnrichDetail_Call) RunAndReturn(run func(ctx context.Context, sp ingest.SourceProperty) (ingest.SourceProperty, error)) *MockSource_EnrichDetail_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockSource
func (_mock *MockSource) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSource_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockSource_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockSource_Expecter) Name() *MockSource_Name_Call {
	return &MockSource_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockSource_Name_Call) Run(run func()) *MockSource_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Name_Call) Return(s string) *MockSource_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSource_Name_Call) RunAndReturn(run func() string) *MockSource_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockSource
func (_mock *MockSource) Search(ctx context.Context, q ingest.SearchQuery) iter.Seq2[ingest.SourceProperty, error] {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 iter.Seq2[ingest.SourceProperty, error]
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.SearchQuery) iter.Seq2[ingest.SourceProperty, error]); ok {
		r0 = returnFunc(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[ingest.SourceProperty, error])
		}
	}
	return r0
}

// MockSource_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSource_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - q ingest.SearchQuery
func (_e *MockSource_Expecter) Search(ctx any, q any) *MockSource_Search_Call {
	return &MockSource_Search_Call{Call: _e.mock.On("Search", ctx, q)}
}

func (_c *MockSource_Search_Call) Run(run func(ctx context.Context, q ingest.SearchQuery)) *MockSource_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ingest.SearchQuery
		if args[1] != nil {
			arg1 = args[1].(ingest.SearchQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_Search_Call) Return(seq2 iter.Seq2[ingest.SourceProperty, error]) *MockSource_Search_Call {
	_c.Call.Return(seq2)
	return _c
}

func (_c *MockSource_Search_Call) RunAndReturn(run func(ctx context.Context, q ingest.SearchQuery) iter.Seq2[ingest.SourceProperty, error]) *MockSource_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// ApplySourceProperty provides a mock function for the type MockStore
func (_mock *MockStore) ApplySourceProperty(ctx context.Context, runID domain.IngestRunID, sp ingest.SourceProperty, observedAt time.Time) (ingest.ApplyResult, error) {
	ret := _mock.Called(ctx, runID, sp, observedAt)

	if len(ret) == 0 {
		panic("no return value specified for ApplySourceProperty")
	}

	var r0 ingest.ApplyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IngestRunID, ingest.SourceProperty, time.Time) (ingest.ApplyResult, error)); ok {
		return returnFunc(ctx, runID, sp, observedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IngestRunID, ingest.SourceProperty, time.Time) ingest.ApplyResult); ok {
		r0 = returnFunc(ctx, runID, sp, observedAt)
	} else {
		r0 = ret.Get(0).(ingest.ApplyResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.IngestRunID, ingest.SourceProperty, time.Time) error); ok {
		r1 = returnFunc(ctx, runID, sp, observedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ApplySourceProperty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplySourceProperty'
type MockStore_ApplySourceProperty_Call struct {
	*mock.Call
}

// ApplySourceProperty is a helper method to define mock.On call
//   - ctx context.Context
//   - runID domain.IngestRunID
//   - sp ingest.SourceProperty
//   - observedAt time.Time
func (_e *MockStore_Expecter) ApplySourceProperty(ctx any, runID any, sp any, observedAt any) *MockStore_ApplySourceProperty_Call {
	return &MockStore_ApplySourceProperty_Call{Call: _e.mock.On("ApplySourceProperty", ctx, runID, sp, observedAt)}
}

func (_c *MockStore_ApplySourceProperty_Call) Run(run func(ctx context.Context, runID domain.IngestRunID, sp ingest.SourceProperty, observedAt time.Time)) *MockStore_ApplySourceProperty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.IngestRunID
		if args[1] != nil {
			arg1 = args[1].(domain.IngestRunID)
		}
		var arg2 ingest.SourceProperty
		if args[2] != nil {
			arg2 = args[2].(ingest.SourceProperty)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_ApplySourceProperty_Call) Return(applyResult ingest.ApplyResult, err error) *MockStore_ApplySourceProperty_Call {
	_c.Call.Return(applyResult, err)
	return _c
}

func (_c *MockStore_ApplySourceProperty_Call) RunAndReturn(run func(ctx context.Context, runID domain.IngestRunID, sp ingest.SourceProperty, observedAt time.Time) (ingest.ApplyResult, error)) *MockStore_ApplySourceProperty_Call {
	_c.Call.Return(run)
	return _c
}

// BaselineVolume provides a mock function for the type MockStore
func (_mock *MockStore) BaselineVolume(ctx context.Context, provider string, scopeHash string) (ingest.Baseline, error) {
	ret := _mock.Called(ctx, provider, scopeHash)

	if len(ret) == 0 {
		panic("no return value specified for BaselineVolume")
	}

	var r0 ingest.Baseline
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (ingest.Baseline, error)); ok {
		return returnFunc(ctx, provider, scopeHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ingest.Baseline); ok {
		r0 = returnFunc(ctx, provider, scopeHash)
	} else {
		r0 = ret.Get(0).(ingest.Baseline)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, scopeHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_BaselineVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaselineVolume'
type MockStore_BaselineVolume_Call struct {
	*mock.Call
}

// BaselineVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - scopeHash string
func (_e *MockStore_Expecter) BaselineVolume(ctx any, provider any, scopeHash any) *MockStore_BaselineVolume_Call {
	return &MockStore_BaselineVolume_Call{Call: _e.mock.On("BaselineVolume", ctx, provider, scopeHash)}
}

func (_c *MockStore_BaselineVolume_Call) Run(run func(ctx context.Context, provider string, scopeHash string)) *MockStore_BaselineVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_BaselineVolume_Call) Return(baseline ingest.Baseline, err error) *MockStore_BaselineVolume_Call {
	_c.Call.Return(baseline, err)
	return _c
}

func (_c *MockStore_BaselineVolume_Call) RunAndReturn(run func(ctx context.Context, provider string, scopeHash string) (ingest.Baseline, error)) *MockStore_BaselineVolume_Call {
	_c.Call.Return(run)
	return _c
}

// EnrichmentState provides a mock function for the type MockStore
func (_mock *MockStore) EnrichmentState(ctx context.Context, provider string, providerID string) (ingest.EnrichState, error) {
	ret := _mock.Called(ctx, provider, providerID)

	if len(ret) == 0 {
		panic("no return value specified for EnrichmentState")
	}

	var r0 ingest.EnrichState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (ingest.EnrichState, error)); ok {
		return returnFunc(ctx, provider, providerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ingest.EnrichState); ok {
		r0 = returnFunc(ctx, provider, providerID)
	} else {
		r0 = ret.Get(0).(ingest.EnrichState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, providerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_EnrichmentState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrichmentState'
type MockStore_EnrichmentState_Call struct {
	*mock.Call
}

// EnrichmentState is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerID string
func (_e *MockStore_Expecter) EnrichmentState(ctx any, provider any, providerID any) *MockStore_EnrichmentState_Call {
	return &MockStore_EnrichmentState_Call{Call: _e.mock.On("EnrichmentState", ctx, provider, providerID)}
}

func (_c *MockStore_EnrichmentState_Call) Run(run func(ctx context.Context, provider string, providerID string)) *MockStore_EnrichmentState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_EnrichmentState_Call) Return(enrichState ingest.EnrichState, err error) *MockStore_EnrichmentState_Call {
	_c.Call.Return(enrichState, err)
	return _c
}

func (_c *MockStore_EnrichmentState_Call) RunAndReturn(run func(ctx context.Context, provider string, providerID string) (ingest.EnrichState, error)) *MockStore_EnrichmentState_Call {
	_c.Call.Return(run)
	return _c
}

// FinishRun provides a mock function for the type MockStore
func (_mock *MockStore) FinishRun(ctx context.Context, id domain.IngestRunID, stats ingest.RunStats) error {
	ret := _mock.Called(ctx, id, stats)

	if len(ret) == 0 {
		panic("no return value specified for FinishRun")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IngestRunID, ingest.RunStats) error); ok {
		r0 = returnFunc(ctx, id, stats)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_FinishRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishRun'
type MockStore_FinishRun_Call struct {
	*mock.Call
}

// FinishRun is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.IngestRunID
//   - stats ingest.RunStats
func (_e *MockStore_Expecter) FinishRun(ctx any, id any, stats any) *MockStore_FinishRun_Call {
	return &MockStore_FinishRun_Call{Call: _e.mock.On("FinishRun", ctx, id, stats)}
}

func (_c *MockStore_FinishRun_Call) Run(run func(ctx context.Context, id domain.IngestRunID, stats ingest.RunStats)) *MockStore_FinishRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.IngestRunID
		if args[1] != nil {
			arg1 = args[1].(domain.IngestRunID)
		}
		var arg2 ingest.RunStats
		if args[2] != nil {
			arg2 = args[2].(ingest.RunStats)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_FinishRun_Call) Return(err error) *MockStore_FinishRun_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_FinishRun_Call) RunAndReturn(run func(ctx context.Context, id domain.IngestRunID, stats ingest.RunStats) error) *MockStore_FinishRun_Call {
	_c.Call.Return(run)
	return _c
}

// ForgetPhotoKeys provides a mock function for the type MockStore
func (_mock *MockStore) ForgetPhotoKeys(ctx context.Context, keys []string) (int, error) {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for ForgetPhotoKeys")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (int, error)); ok {
		return returnFunc(ctx, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) int); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ForgetPhotoKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgetPhotoKeys'
type MockStore_ForgetPhotoKeys_Call struct {
	*mock.Call
}

// ForgetPhotoKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockStore_Expecter) ForgetPhotoKeys(ctx any, keys any) *MockStore_ForgetPhotoKeys_Call {
	return &MockStore_ForgetPhotoKeys_Call{Call: _e.mock.On("ForgetPhotoKeys", ctx, keys)}
}

func (_c *MockStore_ForgetPhotoKeys_Call) Run(run func(ctx context.Context, keys []string)) *MockStore_ForgetPhotoKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ForgetPhotoKeys_Call) Return(n int, err error) *MockStore_ForgetPhotoKeys_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_ForgetPhotoKeys_Call) RunAndReturn(run func(ctx context.Context, keys []string) (int, error)) *MockStore_ForgetPhotoKeys_Call {
	_c.Call.Return(run)
	return _c
}

// FreeExpiredCachedPhotos provides a mock function for the type MockStore
func (_mock *MockStore) FreeExpiredCachedPhotos(ctx context.Context, cutoff time.Time, limit int) ([]string, int, error) {
	ret := _mock.Called(ctx, cutoff, limit)

	if len(ret) == 0 {
		panic("no return value specified for FreeExpiredCachedPhotos")
	}

	var r0 []string
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]string, int, error)); ok {
		return returnFunc(ctx, cutoff, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) []string); ok {
		r0 = returnFunc(ctx, cutoff, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) int); ok {
		r1 = returnFunc(ctx, cutoff, limit)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, time.Time, int) error); ok {
		r2 = returnFunc(ctx, cutoff, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStore_FreeExpiredCachedPhotos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FreeExpiredCachedPhotos'
type MockStore_FreeExpiredCachedPhotos_Call struct {
	*mock.Call
}

// FreeExpiredCachedPhotos is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
//   - limit int
func (_e *MockStore_Expecter) FreeExpiredCachedPhotos(ctx any, cutoff any, limit any) *MockStore_FreeExpiredCachedPhotos_Call {
	return &MockStore_FreeExpiredCachedPhotos_Call{Call: _e.mock.On("FreeExpiredCachedPhotos", ctx, cutoff, limit)}
}

func (_c *MockStore_FreeExpiredCachedPhotos_Call) Run(run func(ctx context.Context, cutoff time.Time, limit int)) *MockStore_FreeExpiredCachedPhotos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_FreeExpiredCachedPhotos_Call) Return(strings []string, n int, err error) *MockStore_FreeExpiredCachedPhotos_Call {
	_c.Call.Return(strings, n, err)
	return _c
}

func (_c *MockStore_FreeExpiredCachedPhotos_Call) RunAndReturn(run func(ctx context.Context, cutoff time.Time, limit int) ([]string, int, error)) *MockStore_FreeExpiredCachedPhotos_Call {
	_c.Call.Return(run)
	return _c
}

// MarkMissingSources provides a mock function for the type MockStore
func (_mock *MockStore) MarkMissingSources(ctx context.Context, provider string, seenProviderIDs []string, runID domain.IngestRunID) (ingest.MissingResult, error) {
	ret := _mock.Called(ctx, provider, seenProviderIDs, runID)

	if len(ret) == 0 {
		panic("no return value specified for MarkMissingSources")
	}

	var r0 ingest.MissingResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, domain.IngestRunID) (ingest.MissingResult, error)); ok {
		return returnFunc(ctx, provider, seenProviderIDs, runID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, domain.IngestRunID) ingest.MissingResult); ok {
		r0 = returnFunc(ctx, provider, seenProviderIDs, runID)
	} else {
		r0 = ret.Get(0).(ingest.MissingResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string, domain.IngestRunID) error); ok {
		r1 = returnFunc(ctx, provider, seenProviderIDs, runID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_MarkMissingSources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkMissingSources'
type MockStore_MarkMissingSources_Call struct {
	*mock.Call
}

// MarkMissingSources is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - seenProviderIDs []string
//   - runID domain.IngestRunID
func (_e *MockStore_Expecter) MarkMissingSources(ctx any, provider any, seenProviderIDs any, runID any) *MockStore_MarkMissingSources_Call {
	return &MockStore_MarkMissingSources_Call{Call: _e.mock.On("MarkMissingSources", ctx, provider, seenProviderIDs, runID)}
}

func (_c *MockStore_MarkMissingSources_Call) Run(run func(ctx context.Context, provider string, seenProviderIDs []string, runID domain.IngestRunID)) *MockStore_MarkMissingSources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 domain.IngestRunID
		if args[3] != nil {
			arg3 = args[3].(domain.IngestRunID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_MarkMissingSources_Call) Return(missingResult ingest.MissingResult, err error) *MockStore_MarkMissingSources_Call {
	_c.Call.Return(missingResult, err)
	return _c
}

func (_c *MockStore_MarkMissingSources_Call) RunAndReturn(run func(ctx context.Context, provider string, seenProviderIDs []string, runID domain.IngestRunID) (ingest.MissingResult, error)) *MockStore_MarkMissingSources_Call {
	_c.Call.Return(run)
	return _c
}

// SetPhotoCache provides a mock function for the type MockStore
func (_mock *MockStore) SetPhotoCache(ctx context.Context, id domain.PropertyID, position int, sourceURL string, cachedPath string, mimeType string, width int, height int) error {
	ret := _mock.Called(ctx, id, position, sourceURL, cachedPath, mimeType, width, height)

	if len(ret) == 0 {
		panic("no return value specified for SetPhotoCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PropertyID, int, string, string, string, int, int) error); ok {
		r0 = returnFunc(ctx, id, position, sourceURL, cachedPath, mimeType, width, height)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SetPhotoCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPhotoCache'
type MockStore_SetPhotoCache_Call struct {
	*mock.Call
}

// SetPhotoCache is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.PropertyID
//   - position int
//   - sourceURL string
//   - cachedPath string
//   - mimeType string
//   - width int
//   - height int
func (_e *MockStore_Expecter) SetPhotoCache(ctx any, id any, position any, sourceURL any, cachedPath any, mimeType any, width any, height any) *MockStore_SetPhotoCache_Call {
	return &MockStore_SetPhotoCache_Call{Call: _e.mock.On("SetPhotoCache", ctx, id, position, sourceURL, cachedPath, mimeType, width, height)}
}

func (_c *MockStore_SetPhotoCache_Call) Run(run func(ctx context.Context, id domain.PropertyID, position int, sourceURL string, cachedPath string, mimeType string, width int, height int)) *MockStore_SetPhotoCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PropertyID
		if args[1] != nil {
			arg1 = args[1].(domain.PropertyID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		var arg7 int
		if args[7] != nil {
			arg7 = args[7].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockStore_SetPhotoCache_Call) Return(err error) *MockStore_SetPhotoCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SetPhotoCache_Call) RunAndReturn(run func(ctx context.Context, id domain.PropertyID, position int, sourceURL string, cachedPath string, mimeType string, width int, height int) error) *MockStore_SetPhotoCache_Call {
	_c.Call.Return(run)
	return _c
}

// StartRun provides a mock function for the type MockStore
func (_mock *MockStore) StartRun(ctx context.Context, provider string, q ingest.SearchQuery) (domain.IngestRun, error) {
	ret := _mock.Called(ctx, provider, q)

	if len(ret) == 0 {
		panic("no return value specified for StartRun")
	}

	var r0 domain.IngestRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ingest.SearchQuery) (domain.IngestRun, error)); ok {
		return returnFunc(ctx, provider, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ingest.SearchQuery) domain.IngestRun); ok {
		r0 = returnFunc(ctx, provider, q)
	} else {
		r0 = ret.Get(0).(domain.IngestRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ingest.SearchQuery) error); ok {
		r1 = returnFunc(ctx, provider, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_StartRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartRun'
type MockStore_StartRun_Call struct {
	*mock.Call
}

// StartRun is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - q ingest.SearchQuery
func (_e *MockStore_Expecter) StartRun(ctx any, provider any, q any) *MockStore_StartRun_Call {
	return &MockStore_StartRun_Call{Call: _e.mock.On("StartRun", ctx, provider, q)}
}

func (_c *MockStore_StartRun_Call) Run(run func(ctx context.Context, provider string, q ingest.SearchQuery)) *MockStore_StartRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ingest.SearchQuery
		if args[2] != nil {
			arg2 = args[2].(ingest.SearchQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_StartRun_Call) Return(ingestRun domain.IngestRun, err error) *MockStore_StartRun_Call {
	_c.Call.Return(ingestRun, err)
	return _c
}

func (_c *MockStore_StartRun_Call) RunAndReturn(run func(ctx context.Context, provider string, q ingest.SearchQuery) (domain.IngestRun, error)) *MockStore_StartRun_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTargetStore creates a new instance of MockTargetStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTargetStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTargetStore {
	mock := &MockTargetStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTargetStore is an autogenerated mock type for the TargetStore type
type MockTargetStore struct {
	mock.Mock
}

type MockTargetStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTargetStore) EXPECT() *MockTargetStore_Expecter {
	return &MockTargetStore_Expecter{mock: &_m.Mock}
}

// DueCrawlTargets provides a mock function for the type MockTargetStore
func (_mock *MockTargetStore) DueCrawlTargets(ctx context.Context, standingEvery time.Duration) ([]domain.CrawlTarget, error) {
	ret := _mock.Called(ctx, standingEvery)

	if len(ret) == 0 {
		panic("no return value specified for DueCrawlTargets")
	}

	var r0 []domain.CrawlTarget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) ([]domain.CrawlTarget, error)); ok {
		return returnFunc(ctx, standingEvery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) []domain.CrawlTarget); ok {
		r0 = returnFunc(ctx, standingEvery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CrawlTarget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, standingEvery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTargetStore_DueCrawlTargets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DueCrawlTargets'
type MockTargetStore_DueCrawlTargets_Call struct {
	*mock.Call
}

// DueCrawlTargets is a helper method to define mock.On call
//   - ctx context.Context
//   - standingEvery time.Duration
func (_e *MockTargetStore_Expecter) DueCrawlTargets(ctx any, standingEvery any) *MockTargetStore_DueCrawlTargets_Call {
	return &MockTargetStore_DueCrawlTargets_Call{Call: _e.mock.On("DueCrawlTargets", ctx, standingEvery)}
}

func (_c *MockTargetStore_DueCrawlTargets_Call) Run(run func(ctx context.Context, standingEvery time.Duration)) *MockTargetStore_DueCrawlTargets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTargetStore_DueCrawlTargets_Call) Return(crawlTargets []domain.CrawlTarget, err error) *MockTargetStore_DueCrawlTargets_Call {
	_c.Call.Return(crawlTargets, err)
	return _c
}

func (_c *MockTargetStore_DueCrawlTargets_Call) RunAndReturn(run func(ctx context.Context, standingEvery time.Duration) ([]domain.CrawlTarget, error)) *MockTargetStore_DueCrawlTargets_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTargetRun provides a mock function for the type MockTargetStore
func (_mock *MockTargetStore) MarkTargetRun(ctx context.Context, id domain.CrawlTargetID, runID domain.IngestRunID, deep bool, runErr error) error {
	ret := _mock.Called(ctx, id, runID, deep, runErr)

	if len(ret) == 0 {
		panic("no return value specified for MarkTargetRun")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CrawlTargetID, domain.IngestRunID, bool, error) error); ok {
		r0 = returnFunc(ctx, id, runID, deep, runErr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTargetStore_MarkTargetRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTargetRun'
type MockTargetStore_MarkTargetRun_Call struct {
	*mock.Call
}

// MarkTargetRun is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.CrawlTargetID
//   - runID domain.IngestRunID
//   - deep bool
//   - runErr error
func (_e *MockTargetStore_Expecter) MarkTargetRun(ctx any, id any, runID any, deep any, runErr any) *MockTargetStore_MarkTargetRun_Call {
	return &MockTargetStore_MarkTargetRun_Call{Call: _e.mock.On("MarkTargetRun", ctx, id, runID, deep, runErr)}
}

func (_c *MockTargetStore_MarkTargetRun_Call) Run(run func(ctx context.Context, id domain.CrawlTargetID, runID domain.IngestRunID, deep bool, runErr error)) *MockTargetStore_MarkTargetRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CrawlTargetID
		if args[1] != nil {
			arg1 = args[1].(domain.CrawlTargetID)
		}
		var arg2 domain.IngestRunID
		if args[2] != nil {
			arg2 = args[2].(domain.IngestRunID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 error
		if args[4] != nil {
			arg4 = args[4].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTargetStore_MarkTargetRun_Call) Return(err error) *MockTargetStore_MarkTargetRun_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTargetStore_MarkTargetRun_Call) RunAndReturn(run func(ctx context.Context, id domain.CrawlTargetID, runID domain.IngestRunID, deep bool, runErr error) error) *MockTargetStore_MarkTargetRun_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTargetStarted provides a mock function for the type MockTargetStore
func (_mock *MockTargetStore) MarkTargetStarted(ctx context.Context, id domain.CrawlTargetID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkTargetStarted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CrawlTargetID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTargetStore_MarkTargetStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTargetStarted'
type MockTargetStore_MarkTargetStarted_Call struct {
	*mock.Call
}

// MarkTargetStarted is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.CrawlTargetID
func (_e *MockTargetStore_Expecter) MarkTargetStarted(ctx any, id any) *MockTargetStore_MarkTargetStarted_Call {
	return &MockTargetStore_MarkTargetStarted_Call{Call: _e.mock.On("MarkTargetStarted", ctx, id)}
}

func (_c *MockTargetStore_MarkTargetStarted_Call) Run(run func(ctx context.Context, id domain.CrawlTargetID)) *MockTargetStore_MarkTargetStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CrawlTargetID
		if args[1] != nil {
			arg1 = args[1].(domain.CrawlTargetID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTargetStore_MarkTargetStarted_Call) Return(err error) *MockTargetStore_MarkTargetStarted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTargetStore_MarkTargetStarted_Call) RunAndReturn(run func(ctx context.Context, id domain.CrawlTargetID) error) *MockTargetStore_MarkTargetStarted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPhotoStore creates a new instance of MockPhotoStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPhotoStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPhotoStore {
	mock := &MockPhotoStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPhotoStore is an autogenerated mock type for the PhotoStore type
type MockPhotoStore struct {
	mock.Mock
}

type MockPhotoStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPhotoStore) EXPECT() *MockPhotoStore_Expecter {
	return &MockPhotoStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockPhotoStore
func (_mock *MockPhotoStore) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPhotoStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPhotoStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockPhotoStore_Expecter) Delete(ctx any, key any) *MockPhotoStore_Delete_Call {
	return &MockPhotoStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockPhotoStore_Delete_Call) Run(run func(ctx context.Context, key string)) *MockPhotoStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPhotoStore_Delete_Call) Return(err error) *MockPhotoStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPhotoStore_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockPhotoStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockPhotoStore
func (_mock *MockPhotoStore) Put(ctx context.Context, key string, data []byte, width int, height int) error {
	ret := _mock.Called(ctx, key, data, width, height)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, int, int) error); ok {
		r0 = returnFunc(ctx, key, data, width, height)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPhotoStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockPhotoStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data []byte
//   - width int
//   - height int
func (_e *MockPhotoStore_Expecter) Put(ctx any, key any, data any, width any, height any) *MockPhotoStore_Put_Call {
	return &MockPhotoStore_Put_Call{Call: _e.mock.On("Put", ctx, key, data, width, height)}
}

func (_c *MockPhotoStore_Put_Call) Run(run func(ctx context.Context, key string, data []byte, width int, height int)) *MockPhotoStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPhotoStore_Put_Call) Return(err error) *MockPhotoStore_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPhotoStore_Put_Call) RunAndReturn(run func(ctx context.Context, key string, data []byte, width int, height int) error) *MockPhotoStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockPhotoStore
func (_mock *MockPhotoStore) Stat(ctx context.Context, key string) (photostore.Info, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 photostore.Info
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (photostore.Info, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) photostore.Info); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(photostore.Info)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPhotoStore_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockPhotoStore_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockPhotoStore_Expecter) Stat(ctx any, key any) *MockPhotoStore_Stat_Call {
	return &MockPhotoStore_Stat_Call{Call: _e.mock.On("Stat", ctx, key)}
}

func (_c *MockPhotoStore_Stat_Call) Run(run func(ctx context.Context, key string)) *MockPhotoStore_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPhotoStore_Stat_Call) Return(info photostore.Info, err error) *MockPhotoStore_Stat_Call {
	_c.Call.Return(info, err)
	return _c
}

func (_c *MockPhotoStore_Stat_Call) RunAndReturn(run func(ctx context.Context, key string) (photostore.Info, error)) *MockPhotoStore_Stat_Call {
	_c.Call.Return(run)
	return _c
}
