// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/davidteather/property-radar/internal/domain"
	"github.com/davidteather/property-radar/internal/listings"
	"github.com/davidteather/property-radar/internal/photostore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPhotoStore creates a new instance of MockPhotoStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPhotoStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPhotoStore {
	mock := &MockPhotoStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPhotoStore is an autogenerated mock type for the PhotoStore type
type MockPhotoStore struct {
	mock.Mock
}

type MockPhotoStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPhotoStore) EXPECT() *MockPhotoStore_Expecter {
	return &MockPhotoStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockPhotoStore
func (_mock *MockPhotoStore) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPhotoStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPhotoStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockPhotoStore_Expecter) Get(ctx any, key any) *MockPhotoStore_Get_Call {
	return &MockPhotoStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockPhotoStore_Get_Call) Run(run func(ctx context.Context, key string)) *MockPhotoStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPhotoStore_Get_Call) Return(bytes []byte, err error) *MockPhotoStore_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockPhotoStore_Get_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockPhotoStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockPhotoStore
func (_mock *MockPhotoStore) Stat(ctx context.Context, key string) (photostore.Info, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 photostore.Info
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (photostore.Info, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) photostore.Info); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(photostore.Info)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPhotoStore_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockPhotoStore_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockPhotoStore_Expecter) Stat(ctx any, key any) *MockPhotoStore_Stat_Call {
	return &MockPhotoStore_Stat_Call{Call: _e.mock.On("Stat", ctx, key)}
}

func (_c *MockPhotoStore_Stat_Call) Run(run func(ctx context.Context, key string)) *MockPhotoStore_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPhotoStore_Stat_Call) Return(info photostore.Info, err error) *MockPhotoStore_Stat_Call {
	_c.Call.Return(info, err)
	return _c
}

func (_c *MockPhotoStore_Stat_Call) RunAndReturn(run func(ctx context.Context, key string) (photostore.Info, error)) *MockPhotoStore_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// AddToList provides a mock function for the type MockStore
func (_mock *MockStore) AddToList(ctx context.Context, listID domain.ListID, propertyID domain.PropertyID, note string) (bool, error) {
	ret := _mock.Called(ctx, listID, propertyID, note)

	if len(ret) == 0 {
		panic("no return value specified for AddToList")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListID, domain.PropertyID, string) (bool, error)); ok {
		return returnFunc(ctx, listID, propertyID, note)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListID, domain.PropertyID, string) bool); ok {
		r0 = returnFunc(ctx, listID, propertyID, note)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListID, domain.PropertyID, string) error); ok {
		r1 = returnFunc(ctx, listID, propertyID, note)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_AddToList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToList'
type MockStore_AddToList_Call struct {
	*mock.Call
}

// AddToList is a helper method to define mock.On call
//   - ctx context.Context
//   - listID domain.ListID
//   - propertyID domain.PropertyID
//   - note string
func (_e *MockStore_Expecter) AddToList(ctx any, listID any, propertyID any, note any) *MockStore_AddToList_Call {
	return &MockStore_AddToList_Call{Call: _e.mock.On("AddToList", ctx, listID, propertyID, note)}
}

func (_c *MockStore_AddToList_Call) Run(run func(ctx context.Context, listID domain.ListID, propertyID domain.PropertyID, note string)) *MockStore_AddToList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListID
		if args[1] != nil {
			arg1 = args[1].(domain.ListID)
		}
		var arg2 domain.PropertyID
		if args[2] != nil {
			arg2 = args[2].(domain.PropertyID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_AddToList_Call) Return(b bool, err error) *MockStore_AddToList_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStore_AddToList_Call) RunAndReturn(run func(ctx context.Context, listID domain.ListID, propertyID domain.PropertyID, note string) (bool, error)) *MockStore_AddToList_Call {
	_c.Call.Return(run)
	return _c
}

// AppendRubric provides a mock function for the type MockStore
func (_mock *MockStore) AppendRubric(ctx context.Context, content string, through domain.VerdictID) (domain.Rubric, error) {
	ret := _mock.Called(ctx, content, through)

	if len(ret) == 0 {
		panic("no return value specified for AppendRubric")
	}

	var r0 domain.Rubric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.VerdictID) (domain.Rubric, error)); ok {
		return returnFunc(ctx, content, through)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.VerdictID) domain.Rubric); ok {
		r0 = returnFunc(ctx, content, through)
	} else {
		r0 = ret.Get(0).(domain.Rubric)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.VerdictID) error); ok {
		r1 = returnFunc(ctx, content, through)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_AppendRubric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendRubric'
type MockStore_AppendRubric_Call struct {
	*mock.Call
}

// AppendRubric is a helper method to define mock.On call
//   - ctx context.Context
//   - content string
//   - through domain.VerdictID
func (_e *MockStore_Expecter) AppendRubric(ctx any, content any, through any) *MockStore_AppendRubric_Call {
	return &MockStore_AppendRubric_Call{Call: _e.mock.On("AppendRubric", ctx, content, through)}
}

func (_c *MockStore_AppendRubric_Call) Run(run func(ctx context.Context, content string, through domain.VerdictID)) *MockStore_AppendRubric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.VerdictID
		if args[2] != nil {
			arg2 = args[2].(domain.VerdictID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_AppendRubric_Call) Return(rubric domain.Rubric, err error) *MockStore_AppendRubric_Call {
	_c.Call.Return(rubric, err)
	return _c
}

func (_c *MockStore_AppendRubric_Call) RunAndReturn(run func(ctx context.Context, content string, through domain.VerdictID) (domain.Rubric, error)) *MockStore_AppendRubric_Call {
	_c.Call.Return(run)
	return _c
}

// Candidates provides a mock function for the type MockStore
func (_mock *MockStore) Candidates(ctx context.Context, p domain.Profile, limit int) ([]domain.Property, error) {
	ret := _mock.Called(ctx, p, limit)

	if len(ret) == 0 {
		panic("no return value specified for Candidates")
	}

	var r0 []domain.Property
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profile, int) ([]domain.Property, error)); ok {
		return returnFunc(ctx, p, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profile, int) []domain.Property); ok {
		r0 = returnFunc(ctx, p, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Property)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Profile, int) error); ok {
		r1 = returnFunc(ctx, p, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Candidates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Candidates'
type MockStore_Candidates_Call struct {
	*mock.Call
}

// Candidates is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Profile
//   - limit int
func (_e *MockStore_Expecter) Candidates(ctx any, p any, limit any) *MockStore_Candidates_Call {
	return &MockStore_Candidates_Call{Call: _e.mock.On("Candidates", ctx, p, limit)}
}

func (_c *MockStore_Candidates_Call) Run(run func(ctx context.Context, p domain.Profile, limit int)) *MockStore_Candidates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Profile
		if args[1] != nil {
			arg1 = args[1].(domain.Profile)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Candidates_Call) Return(propertys []domain.Property, err error) *MockStore_Candidates_Call {
	_c.Call.Return(propertys, err)
	return _c
}

func (_c *MockStore_Candidates_Call) RunAndReturn(run func(ctx context.Context, p domain.Profile, limit int) ([]domain.Property, error)) *MockStore_Candidates_Call {
	_c.Call.Return(run)
	return _c
}

// CorpusStats provides a mock function for the type MockStore
func (_mock *MockStore) CorpusStats(ctx context.Context) (domain.CorpusStats, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CorpusStats")
	}

	var r0 domain.CorpusStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.CorpusStats, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.CorpusStats); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.CorpusStats)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CorpusStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CorpusStats'
type MockStore_CorpusStats_Call struct {
	*mock.Call
}

// CorpusStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) CorpusStats(ctx any) *MockStore_CorpusStats_Call {
	return &MockStore_CorpusStats_Call{Call: _e.mock.On("CorpusStats", ctx)}
}

func (_c *MockStore_CorpusStats_Call) Run(run func(ctx context.Context)) *MockStore_CorpusStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_CorpusStats_Call) Return(corpusStats domain.CorpusStats, err error) *MockStore_CorpusStats_Call {
	_c.Call.Return(corpusStats, err)
	return _c
}

func (_c *MockStore_CorpusStats_Call) RunAndReturn(run func(ctx context.Context) (domain.CorpusStats, error)) *MockStore_CorpusStats_Call {
	_c.Call.Return(run)
	return _c
}

// CountProperties provides a mock function for the type MockStore
func (_mock *MockStore) CountProperties(ctx context.Context, f listings.SearchFilter) (int, error) {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for CountProperties")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, listings.SearchFilter) (int, error)); ok {
		return returnFunc(ctx, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, listings.SearchFilter) int); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, listings.SearchFilter) error); ok {
		r1 = returnFunc(ctx, f)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CountProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountProperties'
type MockStore_CountProperties_Call struct {
	*mock.Call
}

// CountProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - f listings.SearchFilter
func (_e *MockStore_Expecter) CountProperties(ctx any, f any) *MockStore_CountProperties_Call {
	return &MockStore_CountProperties_Call{Call: _e.mock.On("CountProperties", ctx, f)}
}

func (_c *MockStore_CountProperties_Call) Run(run func(ctx context.Context, f listings.SearchFilter)) *MockStore_CountProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 listings.SearchFilter
		if args[1] != nil {
			arg1 = args[1].(listings.SearchFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CountProperties_Call) Return(n int, err error) *MockStore_CountProperties_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_CountProperties_Call) RunAndReturn(run func(ctx context.Context, f listings.SearchFilter) (int, error)) *MockStore_CountProperties_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCrawlTarget provides a mock function for the type MockStore
func (_mock *MockStore) CreateCrawlTarget(ctx context.Context, t domain.CrawlTarget) (domain.CrawlTarget, error) {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for CreateCrawlTarget")
	}

	var r0 domain.CrawlTarget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CrawlTarget) (domain.CrawlTarget, error)); ok {
		return returnFunc(ctx, t)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CrawlTarget) domain.CrawlTarget); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Get(0).(domain.CrawlTarget)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CrawlTarget) error); ok {
		r1 = returnFunc(ctx, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateCrawlTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCrawlTarget'
type MockStore_CreateCrawlTarget_Call struct {
	*mock.Call
}

// CreateCrawlTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - t domain.CrawlTarget
func (_e *MockStore_Expecter) CreateCrawlTarget(ctx any, t any) *MockStore_CreateCrawlTarget_Call {
	return &MockStore_CreateCrawlTarget_Call{Call: _e.mock.On("CreateCrawlTarget", ctx, t)}
}

func (_c *MockStore_CreateCrawlTarget_Call) Run(run func(ctx context.Context, t domain.CrawlTarget)) *MockStore_CreateCrawlTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CrawlTarget
		if args[1] != nil {
			arg1 = args[1].(domain.CrawlTarget)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateCrawlTarget_Call) Return(crawlTarget domain.CrawlTarget, err error) *MockStore_CreateCrawlTarget_Call {
	_c.Call.Return(crawlTarget, err)
	return _c
}

func (_c *MockStore_CreateCrawlTarget_Call) RunAndReturn(run func(ctx context.Context, t domain.CrawlTarget) (domain.CrawlTarget, error)) *MockStore_CreateCrawlTarget_Call {
	_c.Call.Return(run)
	return _c
}

// CreateList provides a mock function for the type MockStore
func (_mock *MockStore) CreateList(ctx context.Context, name string, emoji string) (domain.List, error) {
	ret := _mock.Called(ctx, name, emoji)

	if len(ret) == 0 {
		panic("no return value specified for CreateList")
	}

	var r0 domain.List
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (domain.List, error)); ok {
		return returnFunc(ctx, name, emoji)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) domain.List); ok {
		r0 = returnFunc(ctx, name, emoji)
	} else {
		r0 = ret.Get(0).(domain.List)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, emoji)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateList'
type MockStore_CreateList_Call struct {
	*mock.Call
}

// CreateList is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - emoji string
func (_e *MockStore_Expecter) CreateList(ctx any, name any, emoji any) *MockStore_CreateList_Call {
	return &MockStore_CreateList_Call{Call: _e.mock.On("CreateList", ctx, name, emoji)}
}

func (_c *MockStore_CreateList_Call) Run(run func(ctx context.Context, name string, emoji string)) *MockStore_CreateList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_CreateList_Call) Return(list domain.List, err error) *MockStore_CreateList_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockStore_CreateList_Call) RunAndReturn(run func(ctx context.Context, name string, emoji string) (domain.List, error)) *MockStore_CreateList_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCrawlTarget provides a mock function for the type MockStore
func (_mock *MockStore) DeleteCrawlTarget(ctx context.Context, id domain.CrawlTargetID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCrawlTarget")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CrawlTargetID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteCrawlTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCrawlTarget'
type MockStore_DeleteCrawlTarget_Call struct {
	*mock.Call
}

// DeleteCrawlTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.CrawlTargetID
func (_e *MockStore_Expecter) DeleteCrawlTarget(ctx any, id any) *MockStore_DeleteCrawlTarget_Call {
	return &MockStore_DeleteCrawlTarget_Call{Call: _e.mock.On("DeleteCrawlTarget", ctx, id)}
}

func (_c *MockStore_DeleteCrawlTarget_Call) Run(run func(ctx context.Context, id domain.CrawlTargetID)) *MockStore_DeleteCrawlTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CrawlTargetID
		if args[1] != nil {
			arg1 = args[1].(domain.CrawlTargetID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteCrawlTarget_Call) Return(err error) *MockStore_DeleteCrawlTarget_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteCrawlTarget_Call) RunAndReturn(run func(ctx context.Context, id domain.CrawlTargetID) error) *MockStore_DeleteCrawlTarget_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteList provides a mock function for the type MockStore
func (_mock *MockStore) DeleteList(ctx context.Context, id domain.ListID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteList")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteList'
type MockStore_DeleteList_Call struct {
	*mock.Call
}

// DeleteList is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ListID
func (_e *MockStore_Expecter) DeleteList(ctx any, id any) *MockStore_DeleteList_Call {
	return &MockStore_DeleteList_Call{Call: _e.mock.On("DeleteList", ctx, id)}
}

func (_c *MockStore_DeleteList_Call) Run(run func(ctx context.Context, id domain.ListID)) *MockStore_DeleteList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListID
		if args[1] != nil {
			arg1 = args[1].(domain.ListID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteList_Call) Return(err error) *MockStore_DeleteList_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteList_Call) RunAndReturn(run func(ctx context.Context, id domain.ListID) error) *MockStore_DeleteList_Call {
	_c.Call.Return(run)
	return _c
}

// GetCrawlTarget provides a mock function for the type MockStore
func (_mock *MockStore) GetCrawlTarget(ctx context.Context, id domain.CrawlTargetID) (domain.CrawlTarget, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCrawlTarget")
	}

	var r0 domain.CrawlTarget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CrawlTargetID) (domain.CrawlTarget, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CrawlTargetID) domain.CrawlTarget); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.CrawlTarget)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CrawlTargetID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetCrawlTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCrawlTarget'
type MockStore_GetCrawlTarget_Call struct {
	*mock.Call
}

// GetCrawlTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.CrawlTargetID
func (_e *MockStore_Expecter) GetCrawlTarget(ctx any, id any) *MockStore_GetCrawlTarget_Call {
	return &MockStore_GetCrawlTarget_Call{Call: _e.mock.On("GetCrawlTarget", ctx, id)}
}

func (_c *MockStore_GetCrawlTarget_Call) Run(run func(ctx context.Context, id domain.CrawlTargetID)) *MockStore_GetCrawlTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CrawlTargetID
		if args[1] != nil {
			arg1 = args[1].(domain.CrawlTargetID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetCrawlTarget_Call) Return(crawlTarget domain.CrawlTarget, err error) *MockStore_GetCrawlTarget_Call {
	_c.Call.Return(crawlTarget, err)
	return _c
}

func (_c *MockStore_GetCrawlTarget_Call) RunAndReturn(run func(ctx context.Context, id domain.CrawlTargetID) (domain.CrawlTarget, error)) *MockStore_GetCrawlTarget_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function for the type MockStore
func (_mock *MockStore) GetList(ctx context.Context, id domain.ListID) (domain.List, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 domain.List
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListID) (domain.List, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListID) domain.List); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.List)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockStore_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ListID
func (_e *MockStore_Expecter) GetList(ctx any, id any) *MockStore_GetList_Call {
	return &MockStore_GetList_Call{Call: _e.mock.On("GetList", ctx, id)}
}

func (_c *MockStore_GetList_Call) Run(run func(ctx context.Context, id domain.ListID)) *MockStore_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListID
		if args[1] != nil {
			arg1 = args[1].(domain.ListID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetList_Call) Return(list domain.List, err error) *MockStore_GetList_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockStore_GetList_Call) RunAndReturn(run func(ctx context.Context, id domain.ListID) (domain.List, error)) *MockStore_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// GetListBySlug provides a mock function for the type MockStore
func (_mock *MockStore) GetListBySlug(ctx context.Context, slug string) (domain.List, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetListBySlug")
	}

	var r0 domain.List
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.List, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.List); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		r0 = ret.Get(0).(domain.List)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetListBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListBySlug'
type MockStore_GetListBySlug_Call struct {
	*mock.Call
}

// GetListBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockStore_Expecter) GetListBySlug(ctx any, slug any) *MockStore_GetListBySlug_Call {
	return &MockStore_GetListBySlug_Call{Call: _e.mock.On("GetListBySlug", ctx, slug)}
}

func (_c *MockStore_GetListBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockStore_GetListBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetListBySlug_Call) Return(list domain.List, err error) *MockStore_GetListBySlug_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockStore_GetListBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (domain.List, error)) *MockStore_GetListBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function for the type MockStore
func (_mock *MockStore) GetProfile(ctx context.Context) (domain.Profile, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 domain.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.Profile, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.Profile); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.Profile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockStore_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetProfile(ctx any) *MockStore_GetProfile_Call {
	return &MockStore_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx)}
}

func (_c *MockStore_GetProfile_Call) Run(run func(ctx context.Context)) *MockStore_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_GetProfile_Call) Return(profile domain.Profile, err error) *MockStore_GetProfile_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockStore_GetProfile_Call) RunAndReturn(run func(ctx context.Context) (domain.Profile, error)) *MockStore_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProperty provides a mock function for the type MockStore
func (_mock *MockStore) GetProperty(ctx context.Context, id domain.PropertyID) (domain.Property, []domain.PriceEvent, []domain.Photo, listings.ProvenanceSummary, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProperty")
	}

	var r0 domain.Property
	var r1 []domain.PriceEvent
	var r2 []domain.Photo
	var r3 listings.ProvenanceSummary
	var r4 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PropertyID) (domain.Property, []domain.PriceEvent, []domain.Photo, listings.ProvenanceSummary, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PropertyID) domain.Property); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Property)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PropertyID) []domain.PriceEvent); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]domain.PriceEvent)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.PropertyID) []domain.Photo); ok {
		r2 = returnFunc(ctx, id)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]domain.Photo)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, domain.PropertyID) listings.ProvenanceSummary); ok {
		r3 = returnFunc(ctx, id)
	} else {
		r3 = ret.Get(3).(listings.ProvenanceSummary)
	}
	if returnFunc, ok := ret.Get(4).(func(context.Context, domain.PropertyID) error); ok {
		r4 = returnFunc(ctx, id)
	} else {
		r4 = ret.Error(4)
	}
	return r0, r1, r2, r3, r4
}

// MockStore_GetProperty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProperty'
type MockStore_GetProperty_Call struct {
	*mock.Call
}

// GetProperty is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.PropertyID
func (_e *MockStore_Expecter) GetProperty(ctx any, id any) *MockStore_GetProperty_Call {
	return &MockStore_GetProperty_Call{Call: _e.mock.On("GetProperty", ctx, id)}
}

func (_c *MockStore_GetProperty_Call) Run(run func(ctx context.Context, id domain.PropertyID)) *MockStore_GetProperty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PropertyID
		if args[1] != nil {
			arg1 = args[1].(domain.PropertyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetProperty_Call) Return(property domain.Property, priceEvents []domain.PriceEvent, photos []domain.Photo, provenanceSummary listings.ProvenanceSummary, err error) *MockStore_GetProperty_Call {
	_c.Call.Return(property, priceEvents, photos, provenanceSummary, err)
	return _c
}

func (_c *MockStore_GetProperty_Call) RunAndReturn(run func(ctx context.Context, id domain.PropertyID) (domain.Property, []domain.PriceEvent, []domain.Photo, listings.ProvenanceSummary, error)) *MockStore_GetProperty_Call {
	_c.Call.Return(run)
	return _c
}

// ListCrawlTargets provides a mock function for the type MockStore
func (_mock *MockStore) ListCrawlTargets(ctx context.Context) ([]domain.CrawlTarget, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCrawlTargets")
	}

	var r0 []domain.CrawlTarget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.CrawlTarget, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.CrawlTarget); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CrawlTarget)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListCrawlTargets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCrawlTargets'
type MockStore_ListCrawlTargets_Call struct {
	*mock.Call
}

// ListCrawlTargets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListCrawlTargets(ctx any) *MockStore_ListCrawlTargets_Call {
	return &MockStore_ListCrawlTargets_Call{Call: _e.mock.On("ListCrawlTargets", ctx)}
}

func (_c *MockStore_ListCrawlTargets_Call) Run(run func(ctx context.Context)) *MockStore_ListCrawlTargets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_ListCrawlTargets_Call) Return(crawlTargets []domain.CrawlTarget, err error) *MockStore_ListCrawlTargets_Call {
	_c.Call.Return(crawlTargets, err)
	return _c
}

func (_c *MockStore_ListCrawlTargets_Call) RunAndReturn(run func(ctx context.Context) ([]domain.CrawlTarget, error)) *MockStore_ListCrawlTargets_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function for the type MockStore
func (_mock *MockStore) ListMembers(ctx context.Context, listID domain.ListID) ([]domain.Property, error) {
	ret := _mock.Called(ctx, listID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []domain.Property
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListID) ([]domain.Property, error)); ok {
		return returnFunc(ctx, listID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListID) []domain.Property); ok {
		r0 = returnFunc(ctx, listID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Property)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListID) error); ok {
		r1 = returnFunc(ctx, listID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockStore_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - listID domain.ListID
func (_e *MockStore_Expecter) ListMembers(ctx any, listID any) *MockStore_ListMembers_Call {
	return &MockStore_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, listID)}
}

func (_c *MockStore_ListMembers_Call) Run(run func(ctx context.Context, listID domain.ListID)) *MockStore_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListID
		if args[1] != nil {
			arg1 = args[1].(domain.ListID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListMembers_Call) Return(propertys []domain.Property, err error) *MockStore_ListMembers_Call {
	_c.Call.Return(propertys, err)
	return _c
}

func (_c *MockStore_ListMembers_Call) RunAndReturn(run func(ctx context.Context, listID domain.ListID) ([]domain.Property, error)) *MockStore_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Lists provides a mock function for the type MockStore
func (_mock *MockStore) Lists(ctx context.Context) ([]domain.List, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Lists")
	}

	var r0 []domain.List
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.List, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.List); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.List)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Lists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lists'
type MockStore_Lists_Call struct {
	*mock.Call
}

// Lists is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) Lists(ctx any) *MockStore_Lists_Call {
	return &MockStore_Lists_Call{Call: _e.mock.On("Lists", ctx)}
}

func (_c *MockStore_Lists_Call) Run(run func(ctx context.Context)) *MockStore_Lists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Lists_Call) Return(lists []domain.List, err error) *MockStore_Lists_Call {
	_c.Call.Return(lists, err)
	return _c
}

func (_c *MockStore_Lists_Call) RunAndReturn(run func(ctx context.Context) ([]domain.List, error)) *MockStore_Lists_Call {
	_c.Call.Return(run)
	return _c
}

// ListsForProperty provides a mock function for the type MockStore
func (_mock *MockStore) ListsForProperty(ctx context.Context, propertyID domain.PropertyID) ([]domain.List, error) {
	ret := _mock.Called(ctx, propertyID)

	if len(ret) == 0 {
		panic("no return value specified for ListsForProperty")
	}

	var r0 []domain.List
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PropertyID) ([]domain.List, error)); ok {
		return returnFunc(ctx, propertyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PropertyID) []domain.List); ok {
		r0 = returnFunc(ctx, propertyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.List)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PropertyID) error); ok {
		r1 = returnFunc(ctx, propertyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListsForProperty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListsForProperty'
type MockStore_ListsForProperty_Call struct {
	*mock.Call
}

// ListsForProperty is a helper method to define mock.On call
//   - ctx context.Context
//   - propertyID domain.PropertyID
func (_e *MockStore_Expecter) ListsForProperty(ctx any, propertyID any) *MockStore_ListsForProperty_Call {
	return &MockStore_ListsForProperty_Call{Call: _e.mock.On("ListsForProperty", ctx, propertyID)}
}

func (_c *MockStore_ListsForProperty_Call) Run(run func(ctx context.Context, propertyID domain.PropertyID)) *MockStore_ListsForProperty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PropertyID
		if args[1] != nil {
			arg1 = args[1].(domain.PropertyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListsForProperty_Call) Return(lists []domain.List, err error) *MockStore_ListsForProperty_Call {
	_c.Call.Return(lists, err)
	return _c
}

func (_c *MockStore_ListsForProperty_Call) RunAndReturn(run func(ctx context.Context, propertyID domain.PropertyID) ([]domain.List, error)) *MockStore_ListsForProperty_Call {
	_c.Call.Return(run)
	return _c
}

// MarkShown provides a mock function for the type MockStore
func (_mock *MockStore) MarkShown(ctx context.Context, ids []domain.PropertyID, asOf *time.Time) (int, error) {
	ret := _mock.Called(ctx, ids, asOf)

	if len(ret) == 0 {
		panic("no return value specified for MarkShown")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PropertyID, *time.Time) (int, error)); ok {
		return returnFunc(ctx, ids, asOf)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PropertyID, *time.Time) int); ok {
		r0 = returnFunc(ctx, ids, asOf)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.PropertyID, *time.Time) error); ok {
		r1 = returnFunc(ctx, ids, asOf)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_MarkShown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkShown'
type MockStore_MarkShown_Call struct {
	*mock.Call
}

// MarkShown is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []domain.PropertyID
//   - asOf *time.Time
func (_e *MockStore_Expecter) MarkShown(ctx any, ids any, asOf any) *MockStore_MarkShown_Call {
	return &MockStore_MarkShown_Call{Call: _e.mock.On("MarkShown", ctx, ids, asOf)}
}

func (_c *MockStore_MarkShown_Call) Run(run func(ctx context.Context, ids []domain.PropertyID, asOf *time.Time)) *MockStore_MarkShown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.PropertyID
		if args[1] != nil {
			arg1 = args[1].([]domain.PropertyID)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_MarkShown_Call) Return(n int, err error) *MockStore_MarkShown_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_MarkShown_Call) RunAndReturn(run func(ctx context.Context, ids []domain.PropertyID, asOf *time.Time) (int, error)) *MockStore_MarkShown_Call {
	_c.Call.Return(run)
	return _c
}

// MatchNeighborhoods provides a mock function for the type MockStore
func (_mock *MockStore) MatchNeighborhoods(ctx context.Context, names []string) ([]string, error) {
	ret := _mock.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for MatchNeighborhoods")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return returnFunc(ctx, names)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = returnFunc(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, names)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_MatchNeighborhoods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MatchNeighborhoods'
type MockStore_MatchNeighborhoods_Call struct {
	*mock.Call
}

// MatchNeighborhoods is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
func (_e *MockStore_Expecter) MatchNeighborhoods(ctx any, names any) *MockStore_MatchNeighborhoods_Call {
	return &MockStore_MatchNeighborhoods_Call{Call: _e.mock.On("MatchNeighborhoods", ctx, names)}
}

func (_c *MockStore_MatchNeighborhoods_Call) Run(run func(ctx context.Context, names []string)) *MockStore_MatchNeighborhoods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_MatchNeighborhoods_Call) Return(strings []string, err error) *MockStore_MatchNeighborhoods_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockStore_MatchNeighborhoods_Call) RunAndReturn(run func(ctx context.Context, names []string) ([]string, error)) *MockStore_MatchNeighborhoods_Call {
	_c.Call.Return(run)
	return _c
}

// PhotoCounts provides a mock function for the type MockStore
func (_mock *MockStore) PhotoCounts(ctx context.Context, ids []domain.PropertyID) (map[domain.PropertyID]listings.PhotoCount, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for PhotoCounts")
	}

	var r0 map[domain.PropertyID]listings.PhotoCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PropertyID) (map[domain.PropertyID]listings.PhotoCount, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PropertyID) map[domain.PropertyID]listings.PhotoCount); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.PropertyID]listings.PhotoCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.PropertyID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_PhotoCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PhotoCounts'
type MockStore_PhotoCounts_Call struct {
	*mock.Call
}

// PhotoCounts is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []domain.PropertyID
func (_e *MockStore_Expecter) PhotoCounts(ctx any, ids any) *MockStore_PhotoCounts_Call {
	return &MockStore_PhotoCounts_Call{Call: _e.mock.On("PhotoCounts", ctx, ids)}
}

func (_c *MockStore_PhotoCounts_Call) Run(run func(ctx context.Context, ids []domain.PropertyID)) *MockStore_PhotoCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.PropertyID
		if args[1] != nil {
			arg1 = args[1].([]domain.PropertyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PhotoCounts_Call) Return(propertyIDToPhotoCount map[domain.PropertyID]listings.PhotoCount, err error) *MockStore_PhotoCounts_Call {
	_c.Call.Return(propertyIDToPhotoCount, err)
	return _c
}

func (_c *MockStore_PhotoCounts_Call) RunAndReturn(run func(ctx context.Context, ids []domain.PropertyID) (map[domain.PropertyID]listings.PhotoCount, error)) *MockStore_PhotoCounts_Call {
	_c.Call.Return(run)
	return _c
}

// PhotoKeyAt provides a mock function for the type MockStore
func (_mock *MockStore) PhotoKeyAt(ctx context.Context, id domain.PropertyID, n int) (string, error) {
	ret := _mock.Called(ctx, id, n)

	if len(ret) == 0 {
		panic("no return value specified for PhotoKeyAt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PropertyID, int) (string, error)); ok {
		return returnFunc(ctx, id, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PropertyID, int) string); ok {
		r0 = returnFunc(ctx, id, n)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PropertyID, int) error); ok {
		r1 = returnFunc(ctx, id, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_PhotoKeyAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PhotoKeyAt'
type MockStore_PhotoKeyAt_Call struct {
	*mock.Call
}

// PhotoKeyAt is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.PropertyID
//   - n int
func (_e *MockStore_Expecter) PhotoKeyAt(ctx any, id any, n any) *MockStore_PhotoKeyAt_Call {
	return &MockStore_PhotoKeyAt_Call{Call: _e.mock.On("PhotoKeyAt", ctx, id, n)}
}

func (_c *MockStore_PhotoKeyAt_Call) Run(run func(ctx context.Context, id domain.PropertyID, n int)) *MockStore_PhotoKeyAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PropertyID
		if args[1] != nil {
			arg1 = args[1].(domain.PropertyID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_PhotoKeyAt_Call) Return(s string, err error) *MockStore_PhotoKeyAt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStore_PhotoKeyAt_Call) RunAndReturn(run func(ctx context.Context, id domain.PropertyID, n int) (string, error)) *MockStore_PhotoKeyAt_Call {
	_c.Call.Return(run)
	return _c
}

// PriceDrops provides a mock function for the type MockStore
func (_mock *MockStore) PriceDrops(ctx context.Context, ids []domain.PropertyID) (map[domain.PropertyID]bool, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for PriceDrops")
	}

	var r0 map[domain.PropertyID]bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PropertyID) (map[domain.PropertyID]bool, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PropertyID) map[domain.PropertyID]bool); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.PropertyID]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.PropertyID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_PriceDrops_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PriceDrops'
type MockStore_PriceDrops_Call struct {
	*mock.Call
}

// PriceDrops is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []domain.PropertyID
func (_e *MockStore_Expecter) PriceDrops(ctx any, ids any) *MockStore_PriceDrops_Call {
	return &MockStore_PriceDrops_Call{Call: _e.mock.On("PriceDrops", ctx, ids)}
}

func (_c *MockStore_PriceDrops_Call) Run(run func(ctx context.Context, ids []domain.PropertyID)) *MockStore_PriceDrops_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.PropertyID
		if args[1] != nil {
			arg1 = args[1].([]domain.PropertyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PriceDrops_Call) Return(propertyIDToBool map[domain.PropertyID]bool, err error) *MockStore_PriceDrops_Call {
	_c.Call.Return(propertyIDToBool, err)
	return _c
}

func (_c *MockStore_PriceDrops_Call) RunAndReturn(run func(ctx context.Context, ids []domain.PropertyID) (map[domain.PropertyID]bool, error)) *MockStore_PriceDrops_Call {
	_c.Call.Return(run)
	return _c
}

// PromoteCrawlTargetToStanding provides a mock function for the type MockStore
func (_mock *MockStore) PromoteCrawlTargetToStanding(ctx context.Context, id domain.CrawlTargetID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PromoteCrawlTargetToStanding")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CrawlTargetID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_PromoteCrawlTargetToStanding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromoteCrawlTargetToStanding'
type MockStore_PromoteCrawlTargetToStanding_Call struct {
	*mock.Call
}

// PromoteCrawlTargetToStanding is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.CrawlTargetID
func (_e *MockStore_Expecter) PromoteCrawlTargetToStanding(ctx any, id any) *MockStore_PromoteCrawlTargetToStanding_Call {
	return &MockStore_PromoteCrawlTargetToStanding_Call{Call: _e.mock.On("PromoteCrawlTargetToStanding", ctx, id)}
}

func (_c *MockStore_PromoteCrawlTargetToStanding_Call) Run(run func(ctx context.Context, id domain.CrawlTargetID)) *MockStore_PromoteCrawlTargetToStanding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CrawlTargetID
		if args[1] != nil {
			arg1 = args[1].(domain.CrawlTargetID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PromoteCrawlTargetToStanding_Call) Return(err error) *MockStore_PromoteCrawlTargetToStanding_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_PromoteCrawlTargetToStanding_Call) RunAndReturn(run func(ctx context.Context, id domain.CrawlTargetID) error) *MockStore_PromoteCrawlTargetToStanding_Call {
	_c.Call.Return(run)
	return _c
}

// PropertiesByIDs provides a mock function for the type MockStore
func (_mock *MockStore) PropertiesByIDs(ctx context.Context, ids []domain.PropertyID) ([]domain.Property, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for PropertiesByIDs")
	}

	var r0 []domain.Property
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PropertyID) ([]domain.Property, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PropertyID) []domain.Property); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Property)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.PropertyID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_PropertiesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PropertiesByIDs'
type MockStore_PropertiesByIDs_Call struct {
	*mock.Call
}

// PropertiesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []domain.PropertyID
func (_e *MockStore_Expecter) PropertiesByIDs(ctx any, ids any) *MockStore_PropertiesByIDs_Call {
	return &MockStore_PropertiesByIDs_Call{Call: _e.mock.On("PropertiesByIDs", ctx, ids)}
}

func (_c *MockStore_PropertiesByIDs_Call) Run(run func(ctx context.Context, ids []domain.PropertyID)) *MockStore_PropertiesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.PropertyID
		if args[1] != nil {
			arg1 = args[1].([]domain.PropertyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PropertiesByIDs_Call) Return(propertys []domain.Property, err error) *MockStore_PropertiesByIDs_Call {
	_c.Call.Return(propertys, err)
	return _c
}

func (_c *MockStore_PropertiesByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []domain.PropertyID) ([]domain.Property, error)) *MockStore_PropertiesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// RecordVerdict provides a mock function for the type MockStore
func (_mock *MockStore) RecordVerdict(ctx context.Context, id domain.PropertyID, kind domain.VerdictKind, note string) (domain.Verdict, error) {
	ret := _mock.Called(ctx, id, kind, note)

	if len(ret) == 0 {
		panic("no return value specified for RecordVerdict")
	}

	var r0 domain.Verdict
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PropertyID, domain.VerdictKind, string) (domain.Verdict, error)); ok {
		return returnFunc(ctx, id, kind, note)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PropertyID, domain.VerdictKind, string) domain.Verdict); ok {
		r0 = returnFunc(ctx, id, kind, note)
	} else {
		r0 = ret.Get(0).(domain.Verdict)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PropertyID, domain.VerdictKind, string) error); ok {
		r1 = returnFunc(ctx, id, kind, note)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_RecordVerdict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordVerdict'
type MockStore_RecordVerdict_Call struct {
	*mock.Call
}

// RecordVerdict is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.PropertyID
//   - kind domain.VerdictKind
//   - note string
func (_e *MockStore_Expecter) RecordVerdict(ctx any, id any, kind any, note any) *MockStore_RecordVerdict_Call {
	return &MockStore_RecordVerdict_Call{Call: _e.mock.On("RecordVerdict", ctx, id, kind, note)}
}

func (_c *MockStore_RecordVerdict_Call) Run(run func(ctx context.Context, id domain.PropertyID, kind domain.VerdictKind, note string)) *MockStore_RecordVerdict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PropertyID
		if args[1] != nil {
			arg1 = args[1].(domain.PropertyID)
		}
		var arg2 domain.VerdictKind
		if args[2] != nil {
			arg2 = args[2].(domain.VerdictKind)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_RecordVerdict_Call) Return(verdict domain.Verdict, err error) *MockStore_RecordVerdict_Call {
	_c.Call.Return(verdict, err)
	return _c
}

func (_c *MockStore_RecordVerdict_Call) RunAndReturn(run func(ctx context.Context, id domain.PropertyID, kind domain.VerdictKind, note string) (domain.Verdict, error)) *MockStore_RecordVerdict_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromList provides a mock function for the type MockStore
func (_mock *MockStore) RemoveFromList(ctx context.Context, listID domain.ListID, propertyID domain.PropertyID) (bool, error) {
	ret := _mock.Called(ctx, listID, propertyID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromList")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListID, domain.PropertyID) (bool, error)); ok {
		return returnFunc(ctx, listID, propertyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListID, domain.PropertyID) bool); ok {
		r0 = returnFunc(ctx, listID, propertyID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListID, domain.PropertyID) error); ok {
		r1 = returnFunc(ctx, listID, propertyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_RemoveFromList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromList'
type MockStore_RemoveFromList_Call struct {
	*mock.Call
}

// RemoveFromList is a helper method to define mock.On call
//   - ctx context.Context
//   - listID domain.ListID
//   - propertyID domain.PropertyID
func (_e *MockStore_Expecter) RemoveFromList(ctx any, listID any, propertyID any) *MockStore_RemoveFromList_Call {
	return &MockStore_RemoveFromList_Call{Call: _e.mock.On("RemoveFromList", ctx, listID, propertyID)}
}

func (_c *MockStore_RemoveFromList_Call) Run(run func(ctx context.Context, listID domain.ListID, propertyID domain.PropertyID)) *MockStore_RemoveFromList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListID
		if args[1] != nil {
			arg1 = args[1].(domain.ListID)
		}
		var arg2 domain.PropertyID
		if args[2] != nil {
			arg2 = args[2].(domain.PropertyID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_RemoveFromList_Call) Return(b bool, err error) *MockStore_RemoveFromList_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStore_RemoveFromList_Call) RunAndReturn(run func(ctx context.Context, listID domain.ListID, propertyID domain.PropertyID) (bool, error)) *MockStore_RemoveFromList_Call {
	_c.Call.Return(run)
	return _c
}

// ResetTasteState provides a mock function for the type MockStore
func (_mock *MockStore) ResetTasteState(ctx context.Context) (listings.ResetCounts, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetTasteState")
	}

	var r0 listings.ResetCounts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (listings.ResetCounts, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) listings.ResetCounts); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(listings.ResetCounts)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ResetTasteState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetTasteState'
type MockStore_ResetTasteState_Call struct {
	*mock.Call
}

// ResetTasteState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ResetTasteState(ctx any) *MockStore_ResetTasteState_Call {
	return &MockStore_ResetTasteState_Call{Call: _e.mock.On("ResetTasteState", ctx)}
}

func (_c *MockStore_ResetTasteState_Call) Run(run func(ctx context.Context)) *MockStore_ResetTasteState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_ResetTasteState_Call) Return(resetCounts listings.ResetCounts, err error) *MockStore_ResetTasteState_Call {
	_c.Call.Return(resetCounts, err)
	return _c
}

func (_c *MockStore_ResetTasteState_Call) RunAndReturn(run func(ctx context.Context) (listings.ResetCounts, error)) *MockStore_ResetTasteState_Call {
	_c.Call.Return(run)
	return _c
}

// RunByID provides a mock function for the type MockStore
func (_mock *MockStore) RunByID(ctx context.Context, id domain.IngestRunID) (domain.IngestRun, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RunByID")
	}

	var r0 domain.IngestRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IngestRunID) (domain.IngestRun, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.IngestRunID) domain.IngestRun); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.IngestRun)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.IngestRunID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_RunByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunByID'
type MockStore_RunByID_Call struct {
	*mock.Call
}

// RunByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.IngestRunID
func (_e *MockStore_Expecter) RunByID(ctx any, id any) *MockStore_RunByID_Call {
	return &MockStore_RunByID_Call{Call: _e.mock.On("RunByID", ctx, id)}
}

func (_c *MockStore_RunByID_Call) Run(run func(ctx context.Context, id domain.IngestRunID)) *MockStore_RunByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.IngestRunID
		if args[1] != nil {
			arg1 = args[1].(domain.IngestRunID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_RunByID_Call) Return(ingestRun domain.IngestRun, err error) *MockStore_RunByID_Call {
	_c.Call.Return(ingestRun, err)
	return _c
}

func (_c *MockStore_RunByID_Call) RunAndReturn(run func(ctx context.Context, id domain.IngestRunID) (domain.IngestRun, error)) *MockStore_RunByID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchProperties provides a mock function for the type MockStore
func (_mock *MockStore) SearchProperties(ctx context.Context, f listings.SearchFilter) ([]domain.Property, error) {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for SearchProperties")
	}

	var r0 []domain.Property
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, listings.SearchFilter) ([]domain.Property, error)); ok {
		return returnFunc(ctx, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, listings.SearchFilter) []domain.Property); ok {
		r0 = returnFunc(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Property)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, listings.SearchFilter) error); ok {
		r1 = returnFunc(ctx, f)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_SearchProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchProperties'
type MockStore_SearchProperties_Call struct {
	*mock.Call
}

// SearchProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - f listings.SearchFilter
func (_e *MockStore_Expecter) SearchProperties(ctx any, f any) *MockStore_SearchProperties_Call {
	return &MockStore_SearchProperties_Call{Call: _e.mock.On("SearchProperties", ctx, f)}
}

func (_c *MockStore_SearchProperties_Call) Run(run func(ctx context.Context, f listings.SearchFilter)) *MockStore_SearchProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 listings.SearchFilter
		if args[1] != nil {
			arg1 = args[1].(listings.SearchFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SearchProperties_Call) Return(propertys []domain.Property, err error) *MockStore_SearchProperties_Call {
	_c.Call.Return(propertys, err)
	return _c
}

func (_c *MockStore_SearchProperties_Call) RunAndReturn(run func(ctx context.Context, f listings.SearchFilter) ([]domain.Property, error)) *MockStore_SearchProperties_Call {
	_c.Call.Return(run)
	return _c
}

// SetCrawlTargetEnabled provides a mock function for the type MockStore
func (_mock *MockStore) SetCrawlTargetEnabled(ctx context.Context, id domain.CrawlTargetID, enabled bool) error {
	ret := _mock.Called(ctx, id, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetCrawlTargetEnabled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CrawlTargetID, bool) error); ok {
		r0 = returnFunc(ctx, id, enabled)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SetCrawlTargetEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCrawlTargetEnabled'
type MockStore_SetCrawlTargetEnabled_Call struct {
	*mock.Call
}

// SetCrawlTargetEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.CrawlTargetID
//   - enabled bool
func (_e *MockStore_Expecter) SetCrawlTargetEnabled(ctx any, id any, enabled any) *MockStore_SetCrawlTargetEnabled_Call {
	return &MockStore_SetCrawlTargetEnabled_Call{Call: _e.mock.On("SetCrawlTargetEnabled", ctx, id, enabled)}
}

func (_c *MockStore_SetCrawlTargetEnabled_Call) Run(run func(ctx context.Context, id domain.CrawlTargetID, enabled bool)) *MockStore_SetCrawlTargetEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CrawlTargetID
		if args[1] != nil {
			arg1 = args[1].(domain.CrawlTargetID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_SetCrawlTargetEnabled_Call) Return(err error) *MockStore_SetCrawlTargetEnabled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SetCrawlTargetEnabled_Call) RunAndReturn(run func(ctx context.Context, id domain.CrawlTargetID, enabled bool) error) *MockStore_SetCrawlTargetEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function for the type MockStore
func (_mock *MockStore) State(ctx context.Context) (domain.Profile, *domain.Rubric, bool, []domain.Verdict, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 domain.Profile
	var r1 *domain.Rubric
	var r2 bool
	var r3 []domain.Verdict
	var r4 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.Profile, *domain.Rubric, bool, []domain.Verdict, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.Profile); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.Profile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *domain.Rubric); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.Rubric)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) bool); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context) []domain.Verdict); ok {
		r3 = returnFunc(ctx)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).([]domain.Verdict)
		}
	}
	if returnFunc, ok := ret.Get(4).(func(context.Context) error); ok {
		r4 = returnFunc(ctx)
	} else {
		r4 = ret.Error(4)
	}
	return r0, r1, r2, r3, r4
}

// MockStore_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockStore_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) State(ctx any) *MockStore_State_Call {
	return &MockStore_State_Call{Call: _e.mock.On("State", ctx)}
}

func (_c *MockStore_State_Call) Run(run func(ctx context.Context)) *MockStore_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_State_Call) Return(profile domain.Profile, rubric *domain.Rubric, b bool, verdicts []domain.Verdict, err error) *MockStore_State_Call {
	_c.Call.Return(profile, rubric, b, verdicts, err)
	return _c
}

func (_c *MockStore_State_Call) RunAndReturn(run func(ctx context.Context) (domain.Profile, *domain.Rubric, bool, []domain.Verdict, error)) *MockStore_State_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockStore
func (_mock *MockStore) UpdateProfile(ctx context.Context, merge func(*domain.Profile) error) (domain.Profile, error) {
	ret := _mock.Called(ctx, merge)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 domain.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(*domain.Profile) error) (domain.Profile, error)); ok {
		return returnFunc(ctx, merge)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(*domain.Profile) error) domain.Profile); ok {
		r0 = returnFunc(ctx, merge)
	} else {
		r0 = ret.Get(0).(domain.Profile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, func(*domain.Profile) error) error); ok {
		r1 = returnFunc(ctx, merge)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockStore_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - merge func(*domain.Profile) error
func (_e *MockStore_Expecter) UpdateProfile(ctx any, merge any) *MockStore_UpdateProfile_Call {
	return &MockStore_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, merge)}
}

func (_c *MockStore_UpdateProfile_Call) Run(run func(ctx context.Context, merge func(*domain.Profile) error)) *MockStore_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(*domain.Profile) error
		if args[1] != nil {
			arg1 = args[1].(func(*domain.Profile) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateProfile_Call) Return(profile domain.Profile, err error) *MockStore_UpdateProfile_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockStore_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, merge func(*domain.Profile) error) (domain.Profile, error)) *MockStore_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}
